name: 更新与提交工作流程

on:
  schedule:
    - cron: '30 0,10 * * *'
  push:
    branches: [ "gh_page" ]
    paths:
      - '.github/workflows/**'

env:
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境至3.10.14
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"

      - name: 安装FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: 创建并激活虚拟环境，安装依赖
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests_html==0.10.0 lxml==5.2.2 lxml_html_clean==0.1.1 pytube==15.0.0 pydub==0.25.1 speechrecognition==3.10.0 pyppeteer==1.0.2 
          pip install baidu-aip==4.16.13
          pip install chardet==5.2.0

#      - name: 下载 chroemium
#        run: |
#          source venv/bin/activate
#          python3 GetYoutubeUrl.py


      - name: 运行主程序
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          source venv/bin/activate
          python3 main.py


      - name: 配置Git
        run: |
          git config --global user.name "snmra"
          git config --global user.email "hppall@163.com"
          git remote set-url origin https://$GITHUB_TOKEN@github.com/smnra/yudoucode.git
        env:
          GITHUB_TOKEN: ${{ secrets.GT_PAT }}

      - name: 提交并推送更改
        run: |
          git pull # 确保本地是最新的
          git add ./docs/index.html # 添加所有改动，根据实际情况调整 
          git add ./docs/v2ray/index.html # 添加所有改动，根据实际情况调整
          git diff-index --quiet HEAD || git commit -m "Automatic update at $(date)" # 只有改动才提交
          git push origin HEAD:$GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GT_PAT }}

      - name: 备注
        run: echo $(date +"%Y-%m-%d %H:%M:%S") "Workflow completed successfully  111"