# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: yudoucode-action

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'

env:
  TZ: Asia/Shanghai


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04 # 指定使用Ubuntu 20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Test FFmpeg
      run: ffmpeg -version


    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  # 每天定时执行
  run-daily:
    runs-on: ubuntu-latest
    steps:
    - name: Run Daily Job
      uses: actions/checkout@v3
      run: |
        python main.py


# 每天定时触发run-daily作业
on:
  schedule:
    - cron:  '0 1 9 * *' # 每天9点触发

