name: yudoucode-action

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 9 * *' # 每天1点触发

env:
  TZ: Asia/Shanghai

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04 # 指定使用Ubuntu 20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Test FFmpeg
      run: ffmpeg -version

    - uses: actions/checkout@v3
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt;
        pip install requests_html==0.10.0
        pip install lxml==5.2.2
        pip install lxml_html_clean==0.1.1
        pip install pytube==15.0.0
        pip install pydub==0.25.1
        pip install speechrecognition==3.10.0
        
    - name: Run Daily Job
      run: |
        python main.py


    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # 使用GITHUB_TOKEN进行身份验证

    - name: Set up Git config
      run: |
        git config user.name "smnra"
        git config user.email "hppall@163.com"

    - name: Update Submodules
      run: |
        git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- v.txt
        git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -m `date +'%Y%m%d_%H%M%S'`
        git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain github refs/heads/master:master


    - name: Add, Commit, and Push
      env:
        # 设置必要的环境变量
        GIT_USER: ${{ github.actor }} # 使用触发工作流的用户
      run: |
        git -c credential.helper="store --file=/tmp/git-credentials" add --ignore-errors -A -f -- v.txt
        git -c credential.helper="store --file=/tmp/git-credentials" commit -m "Auto-commit at $(date +'%Y%m%d_%H%M%S')"
        echo "${{ secrets.GITHUB_TOKEN }}">/tmp/git-credentials
        chmod 600 /tmp/git-credentials # 确保凭据文件权限安全
        git -c credential.helper="store --file=/tmp/git-credentials" push origin HEAD:$GITHUB_REF # 使用GITHUB_REF正确引用当前分支

