name: 更新与提交工作流程

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境至3.10.14 测试错误
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"

      - name: 安装FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: 创建并激活虚拟环境，安装依赖
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests_html==0.10.0 lxml==5.2.2 lxml_html_clean==0.1.1 pytube==15.0.0 pydub==0.25.1 speechrecognition==3.10.0
          pwd
          ls -lah  ./
          echo "创建并激活虚拟环境，安装依赖成功" 

      - name: run python script
        env:
          GITHUB_LOGIN: smnra
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          source venv/bin/activate
          python3 main.py
      - name: config git info
        run: |
          source venv/bin/activate
          git config --global user.email "hppall@163.com"
          git config --global user.name "smnra"
      - name: commit change
        run: |
          source venv/bin/activate
          git checkout main
          git add ./v.txt
          git commit -m "Update from Github Action"
      - name: push change
        env:
          GITHUB_LOGIN: smnra
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
      - name: done
        run: echo 'done
